
version: '3.8'

services:
  dashboard:
    build: .
    container_name: facility-dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./UpDown.xlsm:/app/UpDown.xlsm:ro
    restart: unless-stopped
