version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./UporDown.xlsm:/app/UporDown.xlsm:ro  # Mount your Excel file read-only
    environment:
      - FLASK_ENV=development
