version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/uptimekuma/Data/UporDown.xlsm:/app/UporDown.xlsm
    environment:
      - FLASK_ENV=development
